### ISSUE TITLE
Tweet || Pay > Text

### ISSUE THREAD

**Issue by slvnperron** [mentum/invoked-website#1]
What should be said here? These are all suggestions and we need to pick the right wording
## Title

Private beta registrations are now open (?)
## What you'll get
- Access to our internal development roadmap
- Free cloud credits on public release
- Get access to the private beta
- Free tickets to many invoked.io conferences all around the world

It would be nice for these to be in a carrousel with attractive icons as well?

**Comment by ghost** [comment]
I feel like "Private beta registrations are now open" is too formal.

I'm proposing something closer to "Get private access before everyone else!" (That should be the text of the button)

I agree with the rest.

Carousels are the worst. http://shouldiuseacarousel.com/ and http://www.usefulusability.com/kill-conversion-killing-carousels-now/

**Comment by EFF** [comment]
### Get full access before everyone
- blah
- blah
- blah

[[ Register for private beta ]]  // this representing a button

Registration button clicked ==> Content in the panel switches ! 

### A dime or a tweet

Register to private beta by either showing your <3 on twitter or by giving us a single dollar. 
We'll get back to you in couple of minutes so you can get your access.

[[ Tweet it ]] [[ Pay for it ]]
