### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by slvnperron** [mentum/invoked-website#17]

**Comment by slvnperron** [comment]
https://thenounproject.com/term/gears/60668/

Scale functions not app

**Comment by slvnperron** [comment]
Focus on features

https://thenounproject.com/search/?q=clock

**Comment by slvnperron** [comment]
Open source

https://thenounproject.com/term/teamwork/122463/

**Comment by EFF** [comment]
Perso je ne suis pas fan de mettre des icon pour mettre des icons ..  Il faut que ca ajoute quelque chose et que ca améliore la compréhension

Mais ça c'est vraiment juste mon opinion
