### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by slvnperron** [mentum/invoked-website#3]
# Say hello to the world's first function cloud

**Comment by EFF** [comment]
Love the  "in seconds" !

**Comment by EFF** [comment]
Some people might find "World's first function cloud" pretentious  ?? But in the other hands, it looks badass and will probably get some hype later on !

Anyways, that's why we interview devs before mass market the page

**Comment by slvnperron** [comment]
yeah but I think we should be a little bit cocky, not too much, but a little

**Comment by osylvain** [comment]
Je ne dirais pas nécessairement _scale_ any function. Ça donne l'impression que c'est quelque chose qui devra être fait manuellement par le user alors qu'en réalité on veut que ca se fasse automatiquement. Je pense que deploy and invoke seraient suffisants, de toute façon on va parler de scalability plus loin.

**Comment by osylvain** [comment]
from any language _within_ seconds peut-être à la fin?
