### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by slvnperron** [mentum/invoked-website#7]
## Javascript

``` js
var invoked = require('invoked');
var add = invoked('github/mentum/invoked-samples', 'csharp-addition');
add(5, 10, function(err, result) {
    if (err) console.log('Error: ', err);
    else     console.log('Success: ', result); // Prints 15
});
```
## Csharp

``` csharp
try {
    var add = new Invokable<int>("github/mentum/invoked-samples", "php-addition");
    var result = await add.CallAsync(5, 10);
    Console.WriteLine("Success: {0}", result); // Prints 15
}
catch(Exception e) {
    Console.WriteLine("Error: {0}", e.Message);
}
```
## Curl

``` bash
curl --user 'api:<your api key here>' \
    https://api.invoked.io/github/mentum/invoked-samples/csharp-addition/invoke \
    -F a=5\
    -F b=10
# Outputs 15
```

**Comment by EFF** [comment]
Thanks pal !

**Comment by ghost** [comment]
# Python

``` py
import invoked

with invoked('github/mentum/invoked-samples', 'csharp-addition') as remote_func:
    print remote_func(5, 10)  # outputs 15
```

**Comment by ghost** [comment]
# jQuery

``` js
var url = "https://api.invoked.io/github/mentum/invoked-samples/csharp-addition/invoke?api_key=<your api key here>" 
$.post(url, {a: 5, b: 10}, function(data) {
    $(".result").html(data); // data equals 15
});
```

sly: slightly fixed

**Comment by EFF** [comment]
# GO

``` go

import (
    "fmt"
    "github.com/mentum/invoked"
)

remote_csharp_add := invoked("github/mentum/invoked-samples", "csharp-addition")

res := remote_csharp_add(8, 7)
fmt.Println(<-res)    // prints 15

```

@slvnperron does this looks more async to you ?

**Comment by slvnperron** [comment]
@EFF I'm sooooo noob in GO, peux-tu m'expliquer comment ça marche en async?

**Comment by slvnperron** [comment]
@jackdbernier je suis noob en python aussi, comment ça marche le async?
i.e. on veut du non-blocking right?

**Comment by EFF** [comment]
@slvnperron  me semble que le curl j'aurais eu tendance à faire ça : 

``` bash
-X POST https://api.invoked.io/github/mentum/invoked-samples/csharp-addition/invoke \
    -H 'Content-Type: application/json' \
    -u 'api:<your api key here>'  \
    -d '{"a":5,"b":"10"}' 
```

**Comment by slvnperron** [comment]
@EFF c'est drôle que tu dises ça j'allais justement te poser la question... est-ce qu'on fait des post ou des get?

**Comment by slvnperron** [comment]
In my mind c'est un GET request, tu demandes de l'info, mais en mpeme temps ça roule une function server-side, donc POST ?! je suis mêlé

**Comment by EFF** [comment]
Tu ne demande pas nécessairement de l'info, tu exécute une action .. Mais je comprends ton point !

On était tombé sur un fuck avec l'ordre des params avec le lambdaws instant api pcq on faisait the_clouded_func.apply(arguments) ... mais la on s'en fou un peu pcq on va les parser comme du monde

**Comment by slvnperron** [comment]
tu apportes un excellent point, tu "Invoke"! une action et tu ne demande pas nécessairement de l'info en retour. Allons-y pour des POST!

**Comment by ghost** [comment]
@slvnperron Perso je ferais 2 exemples pour Python (sync and async)... 

async en Python == Pas trop le fun mais surtout pas trop à la une. Si tu check les top libraries... tous sync.

Cependant, je n'ai rien contre l'idée le code va resembler à https://github.com/ross/requests-futures

Pourquoi pas 2 exemples:
- 1 sync pour les [django](https://www.djangoproject.com/)gnauts
- 1 async pour les [Twisted minded](https://twistedmatrix.com/)

**Comment by ghost** [comment]
Aussi on veut clairement du POST parce que des http-client bien requins vont venir nous montre les fesses avec de la cache! Aussi certain moins requins et plus by the book empêches carrément de mettre un body à un get.

Et la grande question de l'idempotence.
